import type { NewsArticle } from "@/types";

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: "1",
    slug: "usd-tang-manh-truoc-inflation-data",
    titleVi: "USD tăng mạnh trước dữ liệu lạm phát Mỹ",
    titleKo: "미국 인플레이션 데이터 앞두고 달러 강세",
    titleZhCN: "美国通胀数据前美元走强",
    titleZhTW: "美國通脹數據前美元走強",
    summaryVi: "Đồng USD tăng lên mức cao nhất 2 tuần khi nhà đầu tư chờ số liệu CPI của Mỹ.",
    summaryKo: "달러가 미국 CPI 데이터를 기다리는 투자자들로 인해 2주 만에 최고치로 올랐습니다.",
    summaryZhCN: "随着投资者等待美国CPI数据，美元升至两周高位。",
    summaryZhTW: "隨著投資者等待美國CPI數據，美元升至兩週高位。",
    tag: "rate",
    publishedAt: "2024-01-15",
    readMinutes: 3,
    trend: "up",
    trendData: [25100, 25150, 25200, 25180, 25250, 25350, 25450],
  },
  {
    id: "2",
    slug: "vcb-dieu-chinh-ty-gia-usd",
    titleVi: "Vietcombank điều chỉnh tỷ giá USD tăng 50 đồng",
    titleKo: "비엣컴뱅크 달러 환율 50동 인상",
    titleZhCN: "越南外贸银行上调美元汇率50越盾",
    titleZhTW: "越南外貿銀行上調美元匯率50越盾",
    summaryVi: "Vietcombank tăng tỷ giá USD mua vào và bán ra, theo sát diễn biến thị trường quốc tế.",
    summaryKo: "비엣컴뱅크가 국제 시장 움직임에 따라 달러 매입·매도 환율을 인상했습니다.",
    summaryZhCN: "越南外贸银行跟随国际市场走势，上调美元买入及卖出汇率。",
    summaryZhTW: "越南外貿銀行跟隨國際市場走勢，上調美元買入及賣出匯率。",
    tag: "bank",
    publishedAt: "2024-01-14",
    readMinutes: 2,
    trend: "up",
    trendData: [25050, 25080, 25100, 25090, 25120, 25150, 25200],
  },
  {
    id: "3",
    slug: "eur-giam-ecb-giu-lai-suat",
    titleVi: "EUR giảm nhẹ sau quyết định giữ nguyên lãi suất của ECB",
    titleKo: "ECB 금리 동결 후 유로 소폭 하락",
    titleZhCN: "欧央行维持利率不变后欧元小幅下跌",
    titleZhTW: "歐央行維持利率不變後歐元小幅下跌",
    summaryVi: "Ngân hàng Trung ương châu Âu giữ nguyên lãi suất, EUR mất giá nhẹ trên thị trường.",
    summaryKo: "유럽중앙은행이 금리를 동결하면서 유로가 시장에서 소폭 약세를 보였습니다.",
    summaryZhCN: "欧洲央行维持利率不变，欧元在市场上温和走低。",
    summaryZhTW: "歐洲央行維持利率不變，歐元在市場上溫和走低。",
    tag: "analysis",
    publishedAt: "2024-01-13",
    readMinutes: 4,
    trend: "down",
    trendData: [27800, 27750, 27700, 27720, 27680, 27650, 27600],
  },
  {
    id: "4",
    slug: "jpy-yeu-do-boj-chinh-sach-long-leo",
    titleVi: "JPY tiếp tục suy yếu vì chính sách tiền tệ lỏng lẻo của BOJ",
    titleKo: "BOJ 완화정책으로 엔화 약세 지속",
    titleZhCN: "日本央行宽松政策导致日元持续走弱",
    titleZhTW: "日本央行寬鬆政策導致日元持續走弱",
    summaryVi: "Ngân hàng Trung ương Nhật Bản duy trì chính sách lãi suất âm, JPY xuống mức thấp mới.",
    summaryKo: "일본은행이 마이너스 금리 정책을 유지하면서 엔화가 새로운 저점으로 떨어졌습니다.",
    summaryZhCN: "日本银行维持负利率政策，日元跌至新低。",
    summaryZhTW: "日本銀行維持負利率政策，日元跌至新低。",
    tag: "rate",
    publishedAt: "2024-01-12",
    readMinutes: 5,
    trend: "down",
    trendData: [163, 162, 161, 160, 159, 158, 157],
  },
  {
    id: "5",
    slug: "nhnn-kiem-soat-ty-gia",
    titleVi: "NHNN tích cực can thiệp để ổn định tỷ giá",
    titleKo: "베트남 중앙은행 환율 안정화 위해 적극 개입",
    titleZhCN: "越南国家银行积极干预稳定汇率",
    titleZhTW: "越南國家銀行積極干預穩定匯率",
    summaryVi: "Ngân hàng Nhà nước Việt Nam bán USD dự trữ để ổn định tỷ giá trên thị trường.",
    summaryKo: "베트남 국가은행이 시장 환율 안정을 위해 달러 외환 보유고를 매각했습니다.",
    summaryZhCN: "越南国家银行抛售美元储备以稳定市场汇率。",
    summaryZhTW: "越南國家銀行拋售美元儲備以穩定市場匯率。",
    tag: "bank",
    publishedAt: "2024-01-11",
    readMinutes: 3,
    trend: "neutral",
    trendData: [25100, 25110, 25090, 25100, 25105, 25100, 25095],
  },
  {
    id: "6",
    slug: "chenh-lech-cho-den-chinh-thuc-thu-hep",
    titleVi: "Chênh lệch tỷ giá chợ đen và chính thức dần thu hẹp",
    titleKo: "공식 환율과 암시장 환율 격차 점차 좁혀져",
    titleZhCN: "官方汇率与黑市汇率差距逐渐缩小",
    titleZhTW: "官方匯率與黑市匯率差距逐漸縮小",
    summaryVi: "Sự can thiệp của NHNN giúp thu hẹp khoảng cách giữa tỷ giá chợ đen và ngân hàng.",
    summaryKo: "국가은행의 개입으로 공식 환율과 암시장 환율의 차이가 좁혀지고 있습니다.",
    summaryZhCN: "国家银行的干预有助于缩小黑市与银行汇率之间的差距。",
    summaryZhTW: "國家銀行的干預有助於縮小黑市與銀行匯率之間的差距。",
    tag: "analysis",
    publishedAt: "2024-01-10",
    readMinutes: 4,
    trend: "neutral",
    trendData: [25600, 25580, 25560, 25550, 25530, 25520, 25500],
  },
];
