import type { NewsArticle } from "@/types";

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: "1",
    slug: "usd-tang-sau-fed-giu-lai-suat",
    titleVi: "USD tăng sau khi Fed giữ nguyên lãi suất lần thứ ba liên tiếp",
    titleKo: "연준 3연속 금리 동결 후 달러 강세",
    titleZhCN: "美联储连续第三次维持利率后美元走强",
    titleZhTW: "聯準會連續第三次維持利率後美元走強",
    summaryVi: "Đồng USD tăng mạnh sau quyết định giữ lãi suất của Fed, nhà đầu tư chờ tín hiệu cắt giảm trong quý 3/2026.",
    summaryKo: "연준의 금리 동결 결정 이후 달러가 강세를 보이며, 투자자들은 2026년 3분기 인하 신호를 기다리고 있습니다.",
    summaryZhCN: "美联储维持利率决定后美元走强，投资者等待2026年第三季度降息信号。",
    summaryZhTW: "聯準會維持利率決定後美元走強，投資者等待2026年第三季度降息訊號。",
    tag: "rate",
    publishedAt: "2026-06-02",
    readMinutes: 3,
    trend: "up",
    trendData: [25300, 25350, 25400, 25380, 25450, 25500, 25560],
  },
  {
    id: "2",
    slug: "vcb-bidv-tang-ty-gia-usd-thang-6",
    titleVi: "Vietcombank và BIDV đồng loạt tăng tỷ giá USD đầu tháng 6",
    titleKo: "비엣컴뱅크·BIDV, 6월 초 달러 환율 동시 인상",
    titleZhCN: "越南外贸银行与BIDV六月初同步上调美元汇率",
    titleZhTW: "越南外貿銀行與BIDV六月初同步上調美元匯率",
    summaryVi: "Hai ngân hàng lớn nhất Việt Nam điều chỉnh tỷ giá USD mua vào và bán ra tăng 80–100 điểm so với tháng trước.",
    summaryKo: "베트남 최대 두 은행이 달러 매입·매도 환율을 전월 대비 80–100포인트 인상했습니다.",
    summaryZhCN: "越南两大银行将美元买入及卖出汇率较上月上调80–100点。",
    summaryZhTW: "越南兩大銀行將美元買入及賣出匯率較上月上調80–100點。",
    tag: "bank",
    publishedAt: "2026-06-01",
    readMinutes: 2,
    trend: "up",
    trendData: [25200, 25250, 25280, 25310, 25350, 25400, 25460],
  },
  {
    id: "3",
    slug: "eur-phuc-hoi-sau-ecb-tang-lai-suat",
    titleVi: "EUR phục hồi sau khi ECB bất ngờ tăng lãi suất thêm 25 điểm cơ bản",
    titleKo: "ECB 예상 밖 25bp 금리 인상 후 유로 반등",
    titleZhCN: "欧央行意外加息25个基点后欧元反弹",
    titleZhTW: "歐央行意外升息25個基點後歐元反彈",
    summaryVi: "Ngân hàng Trung ương châu Âu tăng lãi suất bất ngờ, EUR tăng 0.8% so với USD trong phiên giao dịch đêm qua.",
    summaryKo: "유럽중앙은행의 예상치 못한 금리 인상으로 유로가 전날 거래에서 달러 대비 0.8% 상승했습니다.",
    summaryZhCN: "欧洲央行意外加息，欧元在昨晚交易中对美元上涨0.8%。",
    summaryZhTW: "歐洲央行意外升息，歐元在昨晚交易中對美元上漲0.8%。",
    tag: "analysis",
    publishedAt: "2026-05-28",
    readMinutes: 4,
    trend: "up",
    trendData: [27500, 27480, 27450, 27510, 27580, 27640, 27700],
  },
  {
    id: "4",
    slug: "jpy-hoi-phuc-boj-thay-doi-chinh-sach",
    titleVi: "JPY hồi phục sau tín hiệu BOJ chuẩn bị kết thúc chính sách lãi suất âm",
    titleKo: "BOJ 마이너스 금리 종료 신호 후 엔화 반등",
    titleZhCN: "日本央行释放结束负利率政策信号后日元反弹",
    titleZhTW: "日本央行釋放結束負利率政策訊號後日元反彈",
    summaryVi: "Thống đốc BOJ phát tín hiệu có thể nâng lãi suất trong năm 2026, đồng Yên tăng mạnh từ mức thấp kỷ lục.",
    summaryKo: "BOJ 총재가 2026년 금리 인상 가능성을 시사하면서 엔화가 역대 최저에서 강하게 반등했습니다.",
    summaryZhCN: "日本央行行长暗示2026年可能加息，日元从历史低点强势反弹。",
    summaryZhTW: "日本央行行長暗示2026年可能升息，日元從歷史低點強勢反彈。",
    tag: "rate",
    publishedAt: "2026-05-22",
    readMinutes: 5,
    trend: "up",
    trendData: [157, 158, 160, 163, 161, 159, 156],
  },
  {
    id: "5",
    slug: "nhnn-ban-ngoai-te-on-dinh-ty-gia-quy-2",
    titleVi: "NHNN bán 1.5 tỷ USD dự trữ để bình ổn tỷ giá trong quý 2/2026",
    titleKo: "베트남 중앙은행, 2026년 2분기 환율 안정 위해 15억 달러 매각",
    titleZhCN: "越南国家银行出售15亿美元储备以稳定2026年二季度汇率",
    titleZhTW: "越南國家銀行出售15億美元儲備以穩定2026年二季度匯率",
    summaryVi: "Ngân hàng Nhà nước Việt Nam can thiệp mạnh để kiềm chế đà tăng của USD, giữ tỷ giá trong biên độ kiểm soát.",
    summaryKo: "베트남 국가은행이 달러 상승세를 억제하고 환율을 통제 범위 내로 유지하기 위해 강력히 개입했습니다.",
    summaryZhCN: "越南国家银行强力干预以抑制美元升势，将汇率维持在可控范围内。",
    summaryZhTW: "越南國家銀行強力干預以抑制美元升勢，將匯率維持在可控範圍內。",
    tag: "bank",
    publishedAt: "2026-05-15",
    readMinutes: 3,
    trend: "neutral",
    trendData: [25450, 25430, 25410, 25400, 25420, 25410, 25400],
  },
  {
    id: "6",
    slug: "krw-tang-manh-kinh-te-han-quoc-phuc-hoi",
    titleVi: "KRW tăng mạnh nhờ xuất khẩu bán dẫn Hàn Quốc đạt kỷ lục mới",
    titleKo: "반도체 수출 사상 최고치에 원화 강세",
    titleZhCN: "韩国半导体出口创历史新高推动韩元走强",
    titleZhTW: "韓國半導體出口創歷史新高推動韓元走強",
    summaryVi: "Kim ngạch xuất khẩu chip bán dẫn của Hàn Quốc đạt kỷ lục, KRW tăng giá so với VND lần đầu trong 6 tháng.",
    summaryKo: "한국 반도체 수출액이 사상 최고치를 기록하며 원화가 6개월 만에 처음으로 베트남 동 대비 강세를 보였습니다.",
    summaryZhCN: "韩国半导体出口额创历史新高，韩元6个月来首次对越南盾升值。",
    summaryZhTW: "韓國半導體出口額創歷史新高，韓元6個月來首次對越南盾升值。",
    tag: "analysis",
    publishedAt: "2026-05-10",
    readMinutes: 4,
    trend: "up",
    trendData: [17.8, 17.9, 18.1, 18.3, 18.5, 18.6, 18.8],
  },
];
